version: 2.1
orbs:
  owasp: entur/owasp@0.0.19  # Version of the OWASP Orb

executors:
  java_17:
    docker:
      - image: cimg/openjdk:17.0  # Docker image with Java 17
    working_directory: ~/project  # Working directory

jobs:
  test-java:
    docker:
      - image: cimg/openjdk:17.0  # Docker image for Java 17
    steps:
      - checkout
      - run:
          name: Calculate cache key
          command: |-
            find . -name 'pom.xml' -o -name 'gradlew*' -o -name '*.gradle*' | \
                    sort | xargs cat > /tmp/CIRCLECI_CACHE_KEY
      - restore_cache:
          key: cache-{{ checksum "/tmp/CIRCLECI_CACHE_KEY" }}
      - run:
          command: mvn verify
      - run:
          name: Analyze on SonarQube Cloud
          command: mvn verify sonar:sonar -Dsonar.projectKey=ShivaniAru_DevSecOps
      - store_test_results:
          path: target/surefire-reports
      - save_cache:
          key: cache-{{ checksum "/tmp/CIRCLECI_CACHE_KEY" }}
          paths:
            - ~/.m2/repository

workflows:
  version: 2
  build-and-test:
    jobs:
      - test-java:
          context: SONAR_TOKEN  # Assuming this context contains the necessary SonarQube token
